name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository == 'doocs/awesome-ai'
    steps:
      - name: Sync to gitee.com
        uses: wearerequired/git-mirror-action@master
        env:
            SSH_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
        with:
            source-repo: git@github.com:doocs/awesome-ai.git
            destination-repo: git@gitee.com:Doocs/awesome-ai.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
            gitee-username: yanglbme
            gitee-password: ${{ secrets.GITEE_PASSWORD }}
            gitee-repo: doocs/awesome-ai
            branch: main